version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: do_you_kanji_development
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/do_you_kanji
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development

volumes:
  postgres_volume:
